application: random-wikipedia-sentence
version: 6
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /del82_admin/console/.*
  script: google.appengine.ext.admin.application
  login: admin

- url: /del82_admin/error/.*
  script: main.app
  login: admin

- url: /del82_admin
  script: main.app
  login: admin

- url: .*
  script: main.app


libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest

error_handlers:
  - file: static/500.2.html

  - error_code: over_quota
    file: static/503.2.html

  - error_code: timeout
    file: static/500.2.html

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- notes-on-app-engine\.org
- load-test\.py
- regenerate_error_pages\.py
